image: Visual Studio 2015

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14

install:
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%

before_build:
    - git submodule update --init --recursive

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS% -DPODS_BUILD_GTEST=ON
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure
